# Generated by Django 2.1.5 on 2019-01-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='remuneracao',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='tempo_de_servico',
        ),
    ]
