# Generated by Django 2.1.5 on 2019-01-28 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190128_1420'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='noticia',
            managers=[
            ],
        ),
    ]
